import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author haoy1
 */
public class Rating_Form extends javax.swing.JFrame {

    private String name;
	private DatabaseConnection dbService;
	private String username;
	private int star;
	private int xID;
	private boolean isRestaurant;
	/**
     * Creates new form Rating
     */
    public Rating_Form(String username, int xID, String name, boolean isRestaurant) {
        initComponents();
        this.username = username;
        this.name = name;
        this.xID = xID;
        this.isRestaurant = isRestaurant;
        this.dbService = new DatabaseConnection("golem.csse.rose-hulman.edu", "RestaurantSelection");
     	dbService.connect("haoy1", "Horryno1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabela = new javax.swing.JLabel();
        jLabelb = new javax.swing.JLabel();
        jLabelc = new javax.swing.JLabel();
        jLabeld = new javax.swing.JLabel();
        jLabele = new javax.swing.JLabel();
        jButtone = new javax.swing.JButton();
        jButtond = new javax.swing.JButton();
        jButtonb = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButtonc = new javax.swing.JButton();
        jButtona = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSubmid = new javax.swing.JButton();

        jLabela.setFont(new java.awt.Font("Yu Gothic", 0, 96)); // NOI18N
        jLabela.setText("1");

        jLabelb.setFont(new java.awt.Font("Yu Gothic", 0, 96)); // NOI18N
        jLabelb.setText("2");

        jLabelc.setFont(new java.awt.Font("Yu Gothic", 0, 96)); // NOI18N
        jLabelc.setText("3");

        jLabeld.setFont(new java.awt.Font("Yu Gothic", 0, 96)); // NOI18N
        jLabeld.setForeground(new java.awt.Color(255, 153, 0));
        jLabeld.setText("4");

        jLabele.setFont(new java.awt.Font("Yu Gothic", 0, 96)); // NOI18N
        jLabele.setForeground(new java.awt.Color(255, 51, 0));
        jLabele.setText("5");

        jButtone.setText("Rate");

        jButtond.setText("Rate");

        jButtonb.setText("Rate");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setToolTipText("");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonc.setText("Rate");

        jButtona.setText("Rate");
        jButtona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaActionPerformed(evt);
            }
        });
        
        jButtonb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbActionPerformed(evt);
            }
        });
        
        jButtonc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncActionPerformed(evt);
            }
        });
        
        jButtond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondActionPerformed(evt);
            }
        });
        
        jButtone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneActionPerformed(evt);
            }
        });
        
        jButtonSubmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jButtonSubmidActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("You are rating for: " + this.name);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("You can also leave a comment:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtona)
                    .addComponent(jLabela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelc))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonb)
                        .addGap(144, 144, 144)
                        .addComponent(jButtonc)))
                .addGap(155, 155, 155)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeld)
                    .addComponent(jButtond))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtone)
                    .addComponent(jLabele))
                .addGap(63, 63, 63))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(120, 120, 120)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabela, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelb, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelc, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeld, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabele, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtone)
                    .addComponent(jButtond)
                    .addComponent(jButtonc)
                    .addComponent(jButtonb)
                    .addComponent(jButtona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jButtonSubmid.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonSubmid.setText("Submit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSubmid, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(294, 294, 294))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSubmid, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButtonaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.star = 1;
        System.out.println(this.star);
    }  
    
    private void jButtonbActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.star = 2;
        System.out.println(this.star);
    }
    
    private void jButtoncActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.star = 3;
        System.out.println(this.star);
    }
    
    private void jButtondActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.star = 4;
        System.out.println(this.star);
    }
    
    private void jButtoneActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.star = 5;
        System.out.println(this.star);
    }
    
    private void jButtonSubmidActionPerformed(ActionEvent evt) {
		if(this.isRestaurant) 
			createRestaurantReview(this.star, jTextField1.getText(), this.xID, username);
		else
			createFoodReview(this.star, jTextField1.getText(), this.xID, username);
		JOptionPane.showMessageDialog(null, "You have rated "+ this.name + " with " + this.star + " stars.");
	}
    
    public boolean createRestaurantReview(int star, String reviewText, int restID, String username) {
		// similar as addRestarant
		Connection c = this.dbService.getConnection();
		
		CallableStatement stm = null;
		try {
			stm = c.prepareCall("{call haoy1.CreateRestRate(?,?,?,?)}");
			stm.setInt(1, star);
			stm.setString(2, reviewText);
			stm.setInt(3, restID);
			stm.setString(4, username);
			stm.execute();
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, "Failed to Rate");
			e.printStackTrace();
		}
		return false;
	}
    
    public boolean createFoodReview(int star, String reviewText, int restID, String username) {
		// similar as addRestarant
		Connection c = this.dbService.getConnection();
		
		CallableStatement stm = null;
		try {
			stm = c.prepareCall("{call haoy1.[CreateFoodRate](?,?,?,?)}");
			stm.setInt(1, star);
			stm.setString(2, reviewText);
			stm.setInt(3, restID);
			stm.setString(4, username);
			stm.execute();
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, "Failed to Rate");
			e.printStackTrace();
		}
		return false;
	}
    

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonSubmid;
    private javax.swing.JButton jButtona;
    private javax.swing.JButton jButtonb;
    private javax.swing.JButton jButtonc;
    private javax.swing.JButton jButtond;
    private javax.swing.JButton jButtone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabela;
    private javax.swing.JLabel jLabelb;
    private javax.swing.JLabel jLabelc;
    private javax.swing.JLabel jLabeld;
    private javax.swing.JLabel jLabele;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}

